AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/*'

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

