AllCops:
  TargetRubyVersion: 3.1.1
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bin/*'

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Metrics/AbcSize:
  Exclude:
    - "db/migrations/*.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrations/*.rb"

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
